Workshop 2
Smaktulka/and-workshops pull request #2
Opened 2024-12-23 08:41 UTC by Smaktulka

Add custom exception (DtoScanException), functionality for saving and loading repositories.

2024-12-23 14:01 UTC, elnurmes requested changes
hi, I added a few small comments, pls check it

2024-12-23 14:01 UTC, elnurmes commented on workshop_1/src/main/java/by/andersen/context/AppContext.java
> +        throw new RuntimeException(e);
avoid generic RuntimeException, at least use new IllegalStateException with some message

2024-12-23 14:01 UTC, elnurmes commented on workshop_1/src/main/java/by/andersen/context/RepositoryContext.java
> +      throw new RuntimeException(e);
same here

2024-12-23 14:01 UTC, elnurmes commented on workshop_1/src/main/java/by/andersen/utils/PropertiesUtils.java
> +      properties.load(Files.newInputStream(appPropertiesFile));
use try-with resources here

2024-12-23 14:01 UTC, elnurmes commented on workshop_1/src/main/java/by/andersen/utils/PropertiesUtils.java
> +      throw new RuntimeException(e);
same about exception

2024-12-23 16:42 UTC, Smaktulka commented
Can you please explain, why it is more preferrable to use IllegalStateException? It should increase readability?

2024-12-23 19:31 UTC, elnurmes commented
> Can you please explain, why it is more preferrable to use IllegalStateException? It should increase readability?
You are working with app states and its provides clearer context for this purpose. So in this case IllegalStateException signaling invalid states, which is more related to your context.

2024-12-24 19:35 UTC, elnurmes approved these changes
Hi, you can merge it, great job!

2024-12-25 08:38 UTC, merged